config/routes.rb
Avidstarter::Application.routes.draw do
  resources :submissions, :only => [:create, :destroy]

  devise_for :accounts, :controllers => {:registrations => 'accounts'}
  devise_scope :account do
    get "/sign_in", :to => "devise/sessions#new"
    get "/sign_up", :to => "devise/registrations#new"
    get "/accounts", :to => "devise/accounts#index"
    get "/accounts/:id", :to => "devise/accounts#show"
  end
  get "home/home"
  
  resources :competitions do
    resources :submissions, :only => [:create, :destroy, :index]
  end
  
  resources :accounts do
   resources :notifications
   resources :comments, :only => [:index, :create, :destroy]
  end
  resources :projects do
    member do
      post :publish
      post :unpublish
    end
    resources :notifications
    resources :comments, :only => [:index, :create, :destroy]
  end
  resources :memberships, :only => [:update, :destroy]
  resources :invitations, :only => [:create, :destroy]
  resources :attachments, :only => [:create, :destroy]
  resources :notifications, :only => [:index, :show]

  root :to => 'home#home'

end

app/views/shared/_breadcrumbs.html.haml
%ul.breadcrumb
  %li
    %a{:href => "#{root_url}"} Projects 
    %span.divider /
  -if controller.action_name == "show"
    %li.active
      %a{:href => project_path(@project)}= "#{@project.business_name}"
  -elsif controller.action_name == "edit" || "update"
    %li
      %a{:href => project_path(@project)}= "#{@project.business_name}"
      %span.divider /
    -unless controller.controller_name == "comments" || (controller.controller_name == "notifications" && controller.action_name != "new")
      -unless active_member?(@project) == false
        %li
          %a{:href => edit_project_path(@project)}= "Edit Project"
          %span.divider /
    %li.active
      -if controller.controller_name == "comments"
        %a{:href => project_comments_path(@project)}= "#{@breadcrumb_name.titleize}"
      -elsif controller.controller_name == "notifications"
        -if controller.action_name == "new"
          %a{:href => new_project_notification_path}= "#{@breadcrumb_name.titleize}"
        -else
          %a{:href => project_notifications_path(@project)}= "#{@breadcrumb_name.titleize}"
      -else 
        %a{:href => edit_project_path(@project, :step => @breadcrumb_name)}= "#{@breadcrumb_name.titleize}"

app/views/shared/_notification_form.html.haml
= n.error_messages
.row-fluid
  .span6
    = n.label :title, "Notification Title"
    = n.text_field :title, :class => "span12", :style => "width: 100%; max-width: 100%;"
    = n.label :notification_type, 'Notification Type'
    = n.select :notification_type, ["Recruiting", "Event", "Announcement"], {:include_blank => 'Choose Notification Type'}, :onchange => "showDiv(this)", :prompt => true, :class => "span12", :style => "width: 100%;"
    #notification_dateandtime{:style => "display:none;"}
      = n.label :date, "Event Date and Time"
      .row-fluid
        .span8
          = n.text_field :date, {:include_blank => true, "data-datepicker" => "datepicker", :value => "", :class => "span12", :style => "width: 100%; display: inline-block;" }
        .span4
          = n.text_field :time, {:include_blank => true, :class => "timepicker1 span12", :value => "", :style => "width: 100%; display: inline-block;" }
  .span6
    = n.label :description
    = n.text_area :description, :class => "comment span12", :style => "width: 100%; max-width: 100%; height: 87px; row: 3"    
   
.row-fluid
  .span12
    %center
      = n.submit "Post Notification", :class => "btn btn-primary btn-project minifont"

:javascript
  function showDiv(obj)
  {
      if(obj[obj.selectedIndex].value == 'Event')
      {
          document.getElementById('notification_dateandtime').style.display = 'block';
      }
      else
      {
          document.getElementById('notification_dateandtime').style.display = 'none';
      }
  } 
  
  $(document).ready(function () { 
    $('.timepicker1').timepicker({
        minuteStep: 5,
        showInputs: false,
        disableFocus: true
    });
  });

app/views/shared/_school_info.html.haml
%center
  %img{:src => "/assets/gsu.png"}
%center
  %h2 Welcome to Georgia State University's entrepreneur portal.
  %br
  %h3 By signing up you can start projects, collaborate with peers, request and comment on business plans. All while staying informed of the latest news and events scheduled on your campus.   

app/views/shared/_side_menu.html.haml
#stickybox.sidemenu
  %ul.nav.nav-list
    %center
      = image_tag @project.logo_url(:thumb)
      %h3= @project.business_name
  
    %li.divider
    / (controller.controller_name == "comments" && active_member?(@project) == false || account_signed_in? == false) or
    - if controller.action_name == "show" or active_member?(@project) == false or controller.controller_name == "comments" && active_member?(@project) or (controller.controller_name == "notifications" && controller.action_name != "new")
      - if active_member?(@project)
        %li.nav-header
          Edit Project 
        %li
          %a{:href => edit_project_path(@project)}
            %i.icon-pencil
            Edit This Project 
        %li.divider
      -if @project.business_plan.present?
        %li.nav-header
          Business Plan
        %li
          = link_to "#{raw('<i class="icon-arrow-down"></i>')} Download Business Plan".html_safe, @project.business_plan.url
        %li.divider
      %li.nav-header
        Project Navigation
      %li
        %a{:href => project_path(@project)}
          %i.icon-eye-open
          Project Overview
      %li
        %a{:href => "mailto: #{@project.contact_emails}"}
          %i.icon-envelope
          Email Team
      %li
        %a{:href => project_comments_path(@project)}
          %i.icon-comments-alt
          Comments
      - unless @project.notifications.count == 0 or nil
        %li
          %a{:href => project_notifications_path(@project)}
            %i.icon-bullhorn
            Notifications
      -if controller.controller_name == "projects" && controller.action_name == "show"
        -if active_member?(@project)
          %li.divider
          %li.nav-header
            Project Publish Options
          %center
          -unless @project.published #I had to format it like this because I couldn't figure out how to put a :method => :post in %a{href 
            %li
              = button_to "Publish Project", publish_project_path(@project), :class => "btn btn-primary minifont", :method => :post
          -else
            %li
              = button_to "Unpublish Project", unpublish_project_path(@project), :class => "btn btn-primary minifont", :method => :post
      -else
        %li.divider
        %li.nav-header
          Project Information
        %li
          %i.icon-pushpin
          Business Concept
          %li.minifont{:style => "display: inline-block;"}= "#{truncate(@project.business_concept)}..."
          %p.minifont{:style => "display: inline-block;"}=link_to "#{raw('<i class="icon-zoom-in"></i>')} Read More".html_safe, project_path(@project)
        %li
          %i.icon-briefcase
          Industry
        %li.minifont= @project.industry

        %li
          %i.icon-map-marker
          Location
        %li.minifont= "#{@project.city}, #{@project.state}"
    -else
      %li.nav-header
        Project Overview
      %li
        %a{:href => project_path(@project)}
          %i.icon-eye-open
          Project Overview 
      %li.divider
      %li.nav-header Edit Project Menu
      %li
        %a{:href => edit_project_path(@project, :step => 'General')}
          %i.icon-book
          General Information
      %li
        %a{:href => edit_project_path(@project, :step => 'Memberships')}
          %i.icon-group
          Team Information
      %li
        %a{:href => edit_project_path(@project, :step => 'Attachments')}
          %i.icon-camera
          Attach Media
      %li
        %a{:href => new_project_notification_path(@project)}
          %i.icon-bullhorn
          Post New Notification
      %li.divider
      %li.nav-header
        Project Publish Options
      %center
      -unless @project.published #I had to format it like this because I couldn't figure out how to put a :method => :post in %a{href 
        %li
          = button_to "Publish Project", publish_project_path(@project), :class => "btn btn-primary", :method => :post
      -else
        %li
          = button_to "Unpublish Project", unpublish_project_path(@project), :class => "btn btn-primary", :method => :post

app/views/shared/_side_menu_competition.html.haml
#stickybox.sidemenu
  %ul.nav.nav-list
    %center
      = image_tag @competition.competition_logo_url(:thumb)
      %h4= @competition.competition_name      
    %li.divider
    - if current_account.profile_type == "Admin"
      %li.nav-header
        Edit Competition 
      %li
        %a{:href => edit_competition_path(@competition)}
          %i.icon-pencil
          Edit This Competition
      %li.divider
    - if @competition.accepting_business_plans? && current_account.profile_type != "Admin"
      %li.nav-header
        Accepting Business Plans
      -if current_account.projects.count > 0
        = form_for :submission, url: submissions_path do |n|
          = n.hidden_field :competition_id, :value => @competition.id
          = n.select :project_id, {:projects => business_plan_list}, {}, :style => "width: 100%;"
          = n.submit "Submit Your Business Plan!".html_safe, :class => "btn btn-primary minifont"
      -else
        %li
          = link_to "#{raw('<i class="icon-beaker"></i>')} Start A New Project!".html_safe, new_project_path, :method => :get
      %li.divider
    %li.nav-header
      Current Submissions
    %li
      = link_to "#{raw('<i class="icon-eye-open"></i>')} View Submissions".html_safe, competition_submissions_path(@competition)
    %li.divider
    %li.nav-header
      Competition Details
    %li
      %i.icon-map-marker
      Location
      %address.minifont
        = @competition.location
        %br
        = @competition.city + ", " + @competition.state
    %li{:style => "margin-bottom: 18px;"}
      %i.icon-calendar
      Date & Time of Competition
      .minifont
        = @competition.date.strftime("%A, %B %d, %Y")
        %br
        = @competition.time.strftime("%I:%M %p")
    -if @competition.prize?
      %li
        %i.icon-trophy
        Prize
        .minifont
          = @competition.prize
    -if @competition.additional_info?
      %li.divider
      %li.nav-header
        Additional Information
      = link_to "#{raw('<i class="icon-paper-clip"></i>')} Download Information".html_safe, @competition.additional_info.url, :class => "btn btn-primary"

app/views/shared/_topnavbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
    
      %a.btn.btn-navbar{"data-toggle" => "collapse", "data-target" => ".nav_collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      
        %a.brand.avidfontthick{:style => "font-weight:700; color: #08C; font-size: 22px; text-shadow: 0 1px 0 rgba(255, 255, 255, .1), 0 0 30px rgba(255, 255, 255, .125)", :href => "#{root_url}"}
          Georgia State University
    
      .nav_collapse.nav-collapse.collapse.in
        - if account_signed_in?
          -if current_account.profile_type == "Admin"
            %ul.nav
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  %i.icon-beaker
                  Projects
                  %b.caret
                %ul.dropdown-menu
                  %li.nav-header Project Options
                  %li
                    %a{:href => "#{projects_path}"} 
                      %i.icon-beaker
                      View All Projects
                  %li
                    %a{:href => "#{root_url}"} 
                      %i.icon-beaker
                      View Published Projects
          -else
            %ul.nav
              %li
                %a{:href => "#{root_url}"} 
                  %i.icon-beaker
                  Projects
          %ul.nav
            %li
              %a{:href => "#{notifications_path}"} 
                %i.icon-bullhorn
                Notifications
          %ul.nav
            %li
              %a{:href => "#{accounts_path}"} 
                %i.icon-group
                People
          -if current_account.profile_type == "Admin"
            %ul.nav
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  %i.icon-trophy
                  Competitions
                  %b.caret
                %ul.dropdown-menu
                  %li.nav-header Competition Options
                  %li
                    %a{:href => "#{competitions_path}"} 
                      %i.icon-trophy
                      View Ongoing Competitions
                  %li
                    %a{:href => "#{new_competition_path}"} 
                      %i.icon-plus-sign
                      Post New Competition
          -else
            %ul.nav
              %li
                %a{:href => "#{competitions_path}"} 
                  %i.icon-trophy
                  Competitions
          %ul.nav.pull-right
            %li.divider-vertical
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %i.icon-user
                = current_account.name
                %b.caret
              %ul.dropdown-menu
                %li.nav-header Profile Options
                -if current_account.projects.count > 0
                  %li
                    %a{:href => "#{account_path(current_account.id)}"} 
                      %i.icon-beaker
                      My Projects
                %li
                  %a{:href => "#{edit_account_registration_path}"} 
                    %i.icon-pencil
                    Edit Profile
                %li.divider
                %li
                  =link_to "#{raw('<i class="icon-off"></i>')} Sign Out".html_safe, destroy_account_session_path, :method => :delete
        - else
          %ul.nav
            %li
              %a{:href => "#{root_url}"} 
                %i.icon-beaker
                Projects
          %ul.nav.pull-right
            %li.divider-vertical
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %i.icon-user
                Login / Sign Up
                %b.caret
              %ul.dropdown-menu
                %li.nav-header Profile Settings
                %li
                  %a{:href => "#{sign_in_url}"} 
                    %i.icon-lock
                    Login
                %li
                  %a{:href => "#{sign_up_url}"}
                    %i.icon-edit
                    Sign Up