config/routes.rb
Avidstarter::Application.routes.draw do
  resources :submissions, :only => [:create, :destroy]

  devise_for :accounts, :controllers => {:registrations => 'accounts'}
  devise_scope :account do
    get "/sign_in", :to => "devise/sessions#new"
    get "/sign_up", :to => "devise/registrations#new"
    get "/accounts", :to => "devise/accounts#index"
    get "/accounts/:id", :to => "devise/accounts#show"
  end
  get "home/home"
  
  resources :competitions do
    resources :submissions, :only => [:create, :destroy, :index]
  end
  
  resources :accounts do
   resources :notifications
   resources :comments, :only => [:index, :create, :destroy]
  end
  resources :projects do
    member do
      post :publish
      post :unpublish
    end
    resources :notifications
    resources :comments, :only => [:index, :create, :destroy]
  end
  resources :memberships, :only => [:update, :destroy]
  resources :invitations, :only => [:create, :destroy]
  resources :attachments, :only => [:create, :destroy]
  resources :notifications, :only => [:index, :show]

  root :to => 'home#home'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    
    if account_signed_in?
      @projects = current_account.projects 
      @invitations = current_account.pending_memberships
    end
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_admin_tables.haml
%h4 
  %i.icon-bolt
  Quick Overview
%table.table.table-striped
  %thead
    %tr
      %th
        = 'Projects'
      %th
        = 'Published Projects'
      %th
        = 'Users'
      %th
        = 'Competition Submissions'
  %tbody
    %tr
      %td
        %center
          %a{:href => projects_path()}
            = Project.count
      %td
        %center
          %a{:href => root_url}
            = all_projects.count
      %td
        %center
          %a{:href => accounts_path()}
            = Account.count 
      %td
        %center
          %a{:href => competitions_path()}
            = Submission.count

%h4
  %i.icon-bullhorn
  Notification Overview
%table.table.table-striped
  %thead
    %tr
      %th
        = 'Alerts'
      %th
        = 'Events'
      %th
        = 'Recruiting'
      %th
        = 'Announcement'
  %tbody
    %tr
      %td
        %center
          %a{:href => notifications_path()}
            = Notification.where(:notification_type => "Alert").count
      %td
        %center
          %a{:href => notifications_path()}
            = Notification.where(:notification_type => "Event").count
      %td
        %center
          %a{:href => notifications_path()}
            = Notification.where(:notification_type => "Recruiting").count 
      %td
        %center
          %a{:href => notifications_path()}
            = Notification.where(:notification_type => "Announcement").count

app/views/home/_all_projects_viewers.haml
#main{:role => "main"}
  %ul#project_tiles
    / These are our grid blocks
    - all_projects.each do |project|
      %li
        %a{:href => "#{project_path(project)}", :style => "text-decoration:none; color: #222222"}
          %div{:class => "project#{project.id}_container"}
            %center
              - if project.logo?
                = image_tag project.logo_url(:thumb)
              - else
                %img{:src => "/assets/project_default.png"}
            %center
              %h3= project.business_name
            %h6 
              %i.icon-pushpin
              Business Concept
            %p{:style => "text-align:justify; font-size:11px;"}= project.business_concept
            
        .actions{:style => "margin-top: 10px; color: #666666; background-color: #ffffff"}
          / %span.badge
          /   %a{:href => "#", :style => "color: #ffffff; text-decoration:none;"}
          /     %i.icon-heart-empty
          /     Like
          %span.badge
            %a{:href => "#{project_comments_path(project)}", :style => "color: #ffffff; text-decoration:none;"}
              %i.icon-comments-alt
              Comment
    
          .floatright{:style => "float:right"}
            %span.badge
              %a{:href => "#{project_path(project)}", :style => "color: #ffffff; text-decoration:none;"}
                %i.icon-zoom-in
                Details
            

/ Once the images are loaded, initalize the Wookmark plug-in.
:javascript
  $('#project_tiles').imagesLoaded(function() {
    // Prepare layout options.
    var options = {
      autoResize: true, // This will auto-update the layout when the browser window is resized.
      container: $('#main'), // Optional, used for some extra CSS styling
      offset: 18, // Optional, the distance between grid items
    };

    // Get a reference to your grid items.
    var handler = $('#project_tiles li');

    // Call the layout function.
    handler.wookmark(options);

    // Capture clicks on grid items.
    handler.click(function(){


      // Update the layout.
      handler.wookmark();
    });
  });

app/views/home/_my_projects.html.haml
.row-fluid
  .span12
    %ul.nav.nav-pills.nav-stacked
      %li.dropdown
        %a.dropdown-toggle{:data => ("toggle=dropdown"), :href => "#"}
          .row-fluid
            .span2
              = image_tag project.logo_url(:small_thumb)
            .span10
              %b.caret{:style => "float:right"}
              %p
              %h4= project.business_name
              / %h7{:style => "color: #444444"}
              /   = "project progress:" 
              /   = render :partial => "users/projects/project_progress", :locals => {:project => project}
        %ul.dropdown-menu.pull-right
          %li
            %center
              %a{:href => "#{edit_project_path(project)}", :style => "border-style: none;"}
                = image_tag project.logo_url(:thumb)
          .divider
          %li
            %a{:href => "#{edit_project_path(project, :step => 'General')}"}
              %i.icon-book
              General Information
          %li
            %a{:href => "#{edit_project_path(project, :step => 'Memberships')}"}
              %i.icon-group
              Team Information
          %li
            %a{:href => "#{edit_project_path(project, :step => 'Attachments')}"}
              %i.icon-camera
              Attach Media
          %li
            %a{:href => "#{new_project_notification_path(project)}"}
              %i.icon-bullhorn
              Post New Notification
          .divider
          %li
            %a{:href => "#{project_path(project)}"}
              %i.icon-eye-open
              Project Overview

app/views/home/_notifications.html.haml
.well
  %h4{:style => "margin-bottom:10px;"} Notifications
  %center
    .btn.btn-large{:style => "margin-bottom:18px;"}
      %i.icon-pushpin
      = link_to 'Post a Notification', new_account_notification_path(current_account)
  %center
    %a.btn.btn-small{:href => "#", :style => "margin-bottom:18px;"}
      %i.icon-warning-sign.icon-large
      Priority
    %a.btn.btn-small{:href => "#", :style => "margin-bottom:18px;"}
      %i.icon-bullhorn.icon-large
      Recruiting
    %a.btn.btn-small{:href => "javascript:void(0)", :style => "margin-bottom:18px;"}
      %i.icon-comments-alt.icon-large
      Feedback
    %a.btn.btn-small{:href => "javascript:void(0)", :style => "margin-bottom:18px;"}
      %i.icon-beaker.icon-large
      New Projects
    %a.btn.btn-small{:href => "javascript:void(0)", :style => "margin-bottom:18px;"}
      %i.icon-asterisk.icon-large
      All Notifications  
  .alert.alert-error
    %button.close{:type => "button" }
      ×
    %strong.minifont= "Business Plan Submission ends Tomorrow! (#{Date.tomorrow.to_formatted_s(:long)})"
    .minifont
      Donec ornare egestas enim, non auctor nisi ultrices eu. Mauris vulputate pellentesque ullamcorper. Praesent a sapien ultricies ipsum cras amet.
  .alert.alert-error
    %button.close{:type => "button" }
      ×
    %strong.minifont= "UGA's Next Top Entrepreneur meeting (#{Date.tomorrow.to_formatted_s(:long)})"
    .minifont
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
  .alert.alert-info
    %button.close{:type => "button" }
      ×
    %strong.minifont= "ventureangel's looking for a programmer (apply now!)"
    .minifont
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ornare egestas enim, non auctor nisi ultrices eu. Mauris vulputate pellentesque ullamcorper. Praesent a sapien ultricies ipsum cras amet.
  .alert.alert-success
    %button.close{:type => "button" }
      ×
    %strong.minifont= "#{current_account.name} has commented on your business Plan"
    .minifont
      Donec ornare egestas enim, non auctor nisi ultrices eu. Mauris vulputate pellentesque ullamcorper. Praesent a sapien ultricies ipsum cras amet.
  .alert.alert-success
    %button.close{:type => "button" }
      ×
    %strong.minifont= "#{current_account.name} has commented on your business Plan"
    .minifont
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
  .alert.alert-info
    %button.close{:type => "button" }
      ×
    %strong.minifont= "Collegetraker is looking for a designer (apply now!)"
    .minifont
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ornare egestas enim, non auctor nisi ultrices eu. Mauris vulputate pellentesque ullamcorper.

  %ul.pager
    %li.previous
      %a{:href => "#"}
        &larr; Older
    %li.next
      %a{:href => "#"}
        Newer &rarr;

app/views/home/_profile.html.haml
.well
  %h3= "Hey #{current_account.first_name}!"
  .sidecontent_bar{:style => "margin-top:10px;"}
    .row-fluid
      .span3
        = image_tag current_account.avatar_url(:thumb)
      .span9
        %dl{:style => "margin-bottom:0px; margin-top:0px;"}
          %dt Name:
          %dd= current_account.name
          %dt Social:
          -if current_account.linked_in? == false
            %dd Please edit your profile to add your LinkedIn account
          -else
            %dd
              = link_to "#{raw('<i class="icon-linkedin-sign icon-large"></i>')} LinkedIn".html_safe, linkedinurl(current_account.linked_in), :target => "_blank"
  .sidecontent_bar{:style => "margin-top:10px;"}
    .row-fluid
      .span12{}
        %center
          = link_to "#{raw('<i class="icon-pencil"></i>')} Edit Profile".html_safe, edit_account_registration_path, "data-toggle" => "modal", :class => "btn btn-primary btn-small"

-if current_account.profile_type == "Admin"
  -if upcoming_comps
    .well
      %h4{:style => "margin-bottom:10px;"}
        %i.icon-warning-sign
        Competitions This Week
      - upcoming_comps.each do |comp|
        %a{:href => competition_path(comp)}
          %p= "#{comp.competition_name}" + " (#{comp.date.strftime("%m/%d/%Y")})"
          
      
        
  
  .well
    = render :partial => "home/admin_tables"
-else
  -if current_account.profile_type == "Contributor"
    %center
      .jumbobutton
        = link_to "#{raw('<i class="icon-beaker icon-large"></i>')} Start A New Project!".html_safe, new_project_path, :class => "btn btn-primary btn-large", :method => :get

  -if users_projects.count > 0
    .well
      %h4 My Current Projects
      - users_projects.each do |project|
        = render :partial => "home/my_projects", :locals => {:project => project}

app/views/home/home.html.haml
- if account_signed_in?
  #mainhub.span9
    .well
      #mainhub_content
        .row-fluid
          .span12            
            - @invitations.each do |invitation|
              .well_two{:style => "padding:10px;"}
                .row-fluid
                  .span10                  
                    = "You've been invited to join: "
                    %a{:href => "#{project_path(invitation.project.id)}"}
                      = invitation.project.business_name
                  .span2
                    %div{:style => "float:right"}
                      = "Invited on: " + invitation.created_at.strftime("%m/%d/%Y")
                .minifont
                  = link_to "#{raw('<i class = "icon icon-plus-sign"></i>')} Accept Invitation".html_safe, membership_path(invitation, :membership => { :pending => false}), :method => :put
                  = "/"
                  = link_to "#{raw('<i class = "icon icon-minus-sign"></i>')} Decline Invitation".html_safe, membership_path(invitation), :method => :delete
        
            %h3{:style => "margin-bottom:10px;"} Latest Projects at Georgia State University

            = render :partial => "all_projects_viewers"

- else  
  #mainhub.span9
    .well
      #mainhub_content
        .row-fluid
          .span12
            = render :partial => "all_projects_viewers"
  