config/routes.rb
Avidstarter::Application.routes.draw do
  resources :submissions, :only => [:create, :destroy]

  devise_for :accounts, :controllers => {:registrations => 'accounts'}
  devise_scope :account do
    get "/sign_in", :to => "devise/sessions#new"
    get "/sign_up", :to => "devise/registrations#new"
    get "/accounts", :to => "devise/accounts#index"
    get "/accounts/:id", :to => "devise/accounts#show"
  end
  get "home/home"
  
  resources :competitions do
    resources :submissions, :only => [:create, :destroy, :index]
  end
  
  resources :accounts do
   resources :notifications
   resources :comments, :only => [:index, :create, :destroy]
  end
  resources :projects do
    member do
      post :publish
      post :unpublish
    end
    resources :notifications
    resources :comments, :only => [:index, :create, :destroy]
  end
  resources :memberships, :only => [:update, :destroy]
  resources :invitations, :only => [:create, :destroy]
  resources :attachments, :only => [:create, :destroy]
  resources :notifications, :only => [:index, :show]

  root :to => 'home#home'

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :competition
  belongs_to :project
  attr_accessible :competition_id, :project_id

  validates :project_id, :uniqueness => {:scope => :competition_id}
  validates :competition, :presence => true

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_filter :check_if_loggedin
  # GET /submissions
  # GET /submissions.json
  def index
    @competition = Competition.find(params[:competition_id])
    @submissions = @competition.submissions(:include => :projects)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @submissions }
    end
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    @submission = Submission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @submission }
    end
  end

  # GET /submissions/new
  # GET /submissions/new.json
  def new
    @submission = Submission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @submission }
    end
  end

  # GET /submissions/1/edit
  def edit
    @submission = Submission.find(params[:id])
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(params[:submission])
    
    if @submission.save
      redirect_to :back 
      flash[:notice] = 'Submission was successfully created.'
    else
      redirect_to :back
      flash[:warning] = "Submission was not saved. Possible duplicate submission."
    end
  end

  # PUT /submissions/1
  # PUT /submissions/1.json
  def update
    @submission = Submission.find(params[:id])

    respond_to do |format|
      if @submission.update_attributes(params[:submission])
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
  
  def check_if_loggedin
    redirect_to :root unless account_signed_in?
  end
end

app/views/submissions/_form.html.erb
<%= form_for(@submission) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.haml
#mainhub.span9
  .well
    .row-fluid
      .span12
        %h4.edit_header= "All submissions for #{link_to @competition.competition_name, competition_path(@competition)}".html_safe
        
        %table.table.table-striped
          %thead
            %tr
              %th
                Project Name
              %th
                Team Members
              %th
                Date Submitted
              %th
                Business Plan
              %th
                Comments
              %th
                Submission Actions
          %tbody
            - @submissions.each do |submission|
              %tr
                %td
                  = image_tag submission.project.logo_url(:tiny_thumb)
                  %a{:href => project_path(submission.project.id)}
                    = submission.project.business_name
                %td
                  - submission.project.members.each do |member|
                    %a{:href => account_path(member.id)}
                      %p= member.name
                %td
                  = submission.created_at.strftime("%d/%m/%Y")
                %td
                  = link_to "#{raw('<i class="icon-arrow-down"></i>')} Download Business Plan".html_safe, submission.project.business_plan.url unless submission.project.business_plan.url == nil
                %td
                  %a{:href => project_comments_path(submission.project.id)}
                    %i.icon-comments-alt
                    = "Leave Comment"
                %td
                  -if current_account.profile_type == "Admin" || active_member?(submission.project)
                    = link_to "#{raw('<i class="icon-trash"></i>')} Remove Submission".html_safe, submission, :method => :delete, :data => { :confirm =>'Are you sure?' }

app/views/submissions/new.html.erb
<h1>New submission</h1>

<%= render 'form' %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>