config/routes.rb
Avidstarter::Application.routes.draw do
  resources :submissions, :only => [:create, :destroy]

  devise_for :accounts, :controllers => {:registrations => 'accounts'}
  devise_scope :account do
    get "/sign_in", :to => "devise/sessions#new"
    get "/sign_up", :to => "devise/registrations#new"
    get "/accounts", :to => "devise/accounts#index"
    get "/accounts/:id", :to => "devise/accounts#show"
  end
  get "home/home"
  
  resources :competitions do
    resources :submissions, :only => [:create, :destroy, :index]
  end
  
  resources :accounts do
   resources :notifications
   resources :comments, :only => [:index, :create, :destroy]
  end
  resources :projects do
    member do
      post :publish
      post :unpublish
    end
    resources :notifications
    resources :comments, :only => [:index, :create, :destroy]
  end
  resources :memberships, :only => [:update, :destroy]
  resources :invitations, :only => [:create, :destroy]
  resources :attachments, :only => [:create, :destroy]
  resources :notifications, :only => [:index, :show]

  root :to => 'home#home'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :business_name, :industry, :city, :state, :business_concept, :logo, :remote_logo_url, :business_plan, :video_url, :invitee_attributes, :attachments_attributes, :published, :published_at
  
  mount_uploader :logo, ImageUploader
  mount_uploader :business_plan, BusinessPlanUploader
  
  acts_as_commentable
  
  has_many :memberships, :dependent => :destroy
  has_many :confirmed_memberships, :class_name => 'Membership', :conditions => {:pending => false}
  has_many :members, :through => :confirmed_memberships, :source => :account
  has_many :pending_memberships, :class_name => 'Membership', :conditions => {:pending => true}
  
  accepts_nested_attributes_for :memberships, :reject_if => lambda { |a| a[:email].blank? }, :allow_destroy => true

  has_many :invitations, :dependent => :destroy
 
  accepts_nested_attributes_for :invitations, :allow_destroy => true

  has_many :attachments, :dependent => :destroy
  
  accepts_nested_attributes_for :attachments, :reject_if => lambda { |a| a[:file].blank? && a[:remote_file_url].blank? }, :allow_destroy => true

  has_many :notifications, :as => :notifier, :dependent => :destroy

  has_many :submissions, :dependent => :destroy
  has_many :competitions, :through => :submissions

  validates :business_name, :industry, :city, :state, :business_concept, :presence => true
  validate :membership_already_exists?



  def invitee_attributes=(params)
    unless params[:email].blank?
      email = params[:email].downcase
      @account = Account.find_by_email(email)
      if @account == nil
        existing_invitation = self.invitations.find_by_recipient_email(email)
        if existing_invitation == nil
          params[:name] = "New User" if params[:name].blank?
          invitations.build(:recipient_email => email, :recipient_name => params[:name])
        else 
          ProjectMembers.new_user_membership_invitation(existing_invitation).deliver
        end
      else
        unless self.members.include?(@account)
          memberships.build(:account =>@account)
        else
          @membership_exists = true
        end
      end
    end
  end
  
  # Returns all the member email addresses if they have valid accounts

  def complete?
    return id.present? && logo.present?
  end

  def publish!
    return false if !complete?
    self.update_attributes(:published => true, :published_at => Time.now.utc)
  end

  def unpublish!
    self.update_attributes(:published => false)
  end

  def contact_emails
    self.memberships.where(:pending => "false").map {|m| m.account ? m.account.email : nil }.compact.join(",")
  end

  private
    def membership_already_exists?
      errors.add(:member, "already added to project") if @membership_exists
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :check_if_contributor, :only => [:new, :create, :edit, :update]
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    @project.memberships.build(:account => current_account, :pending => false)
    
    if @project.save
      flash[:notice] = "Project successfully created"
      redirect_to :root
    else
      flash[:warning] = "Project not created"
      render :action => 'new'
    end
  end

  def edit
    step = 'General'
    step = params[:step] if params[:step].present?
    @breadcrumb_name = step
    @project = current_account.projects.find(params[:id], :include => [:attachments, :invitations])
    @project.attachments.build
    rescue ActiveRecord::RecordNotFound
      return redirect_to root_url, :alert => 'You cannot edit this project.'   
  end

  def update
    @project = current_account.projects.find(params[:id])
    @invitations = @project.invitations
    @breadcrumb_name = params[:step]
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project successfully updated"
      redirect_to :back
    else
      flash[:warning] = "Project not saved. Try again."
      render :action => 'edit'
    end
    rescue ActiveRecord::RecordNotFound
      return redirect_to root_url, :alert => 'You cannot edit this project.'   
  end

  def destroy
    @project = current_account.projects.find(params[:id])
    if @project.destroy
      flash[:notice] = "Project successfully deleted"
      redirect_to :root
    else
      flash[:warning] = "Project not deleted"
      redirect_to :root
    end
    rescue ActiveRecord::RecordNotFound
      return redirect_to root_url, :alert => 'You cannot delete this project'
  end
  
  def show
    @project = Project.find(params[:id], :include => [:attachments, :invitations, :comment_threads])
    unless @project.published || current_account.projects.include?(@project)
      return redirect_to root_url, :alert => 'You cannot access this project.'
    end
  end

  # Publishes a project.
  def publish
    @project = current_account.projects.find(params[:id])
    if @project.publish!
      flash[:notice] = 'Your project has been published.'
    else
      flash[:warning] = 'Your project was not published. It must be saved and have a logo to be published.'
    end
    redirect_to root_url
  end

  # Un-Publishes a project.
  def unpublish
    @project = current_account.projects.find(params[:id])
    if @project.unpublish!
      flash[:notice] = 'Your project has been un-published.'
    else
      flash[:warning] = 'Your project was not un-published.'
    end
    redirect_to root_url
  end
  
  def index
    if current_account.profile_type == "Admin"
      @projects = Project.all
    else
      flash[:warning] = 'You cannot access this page.'
      redirect_to root_url
    end
  end
  
  private
  
  def check_if_contributor
    redirect_to :root unless current_account.profile_type == "Contributor"
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def vid_embed_video(video_url)
    if video_url[/(?:http\:\/\/)?(?:www\.)?(vimeo|youtube)\.com\/(?:watch\?v=)?(.*?)(?:\z|$|&)/]
      video_server = $1
      video_path = $2
    else 
      video_url[/(?:https\:\/\/)?(?:www\.)?youtu.be\/([^\?]*)/]
      video_server = "tiny"
      video_path = $1
    end
    if video_server == ("vimeo")
      %Q{<iframe height="250" width="443" src="http://player.vimeo.com/video/#{ video_path }" frameborder="0" allowfullscreen></iframe>}
    else
      %Q{<iframe height="250" width="443" src="http://www.youtube.com/embed/#{ video_path }?wmode=transparent" frameborder="0" allowfullscreen></iframe>}
    end
  end
  
  def editpage_embed_video(video_url)
    if video_url[/(?:http\:\/\/)?(?:www\.)?(vimeo|youtube)\.com\/(?:watch\?v=)?(.*?)(?:\z|$|&)/]
      video_server = $1
      video_path = $2
    else 
      video_url[/(?:https\:\/\/)?(?:www\.)?youtu.be\/([^\?]*)/]
      video_server = "tiny"
      video_path = $1
    end
    if video_server == ("vimeo")
      %Q{<iframe height="173" width="306" src="http://player.vimeo.com/video/#{ video_path }" frameborder="0" allowfullscreen></iframe>}
    else
      %Q{<iframe height="173" width="306" src="http://www.youtube.com/embed/#{ video_path }?wmode=transparent" frameborder="0" allowfullscreen></iframe>}
    end
  end
  
  def vid_link(video_url)
    if video_url[/(?:http\:\/\/)?(?:www\.)?(vimeo|youtube)\.com\/(?:watch\?v=)?(.*?)(?:\z|$|&)/]
      video_server = $1
      video_path = $2
    else 
      video_url[/(?:https\:\/\/)?(?:www\.)?youtu.be\/([^\?]*)/]
      video_server = "tiny"
      video_path = $1
    end
    if video_server == ("vimeo")
      %Q{http://player.vimeo.com/video/#{ video_path }}
    else
      %Q{http://www.youtube.com/embed/#{ video_path }?wmode=transparent}
    end
  end
  
  def truncate(text, max_sentences = 2, max_words = 40)
    # Take first 2 setences (blah. blah. blah)
    three_sentences = text.split('. ').slice(0, max_sentences).join('. ')
    # Take first 30 words of the above
    shortened = three_sentences.split(' ').slice(0, max_words).join(' ')
    return shortened
  end
  
end

app/views/projects/_attachments.html.haml
.row-fluid
  .span6
    %h3 Existing Media
    
    - @project.attachments.each do |attachment|
      - unless attachment.new_record?
        .image_container{:style => "background-image: url(#{attachment.file_url(:thumb)})"}
          .imagelink_top{:style => "height:50px; width:100px; float: left; clear:both;"}  
            %a{:href => attachment.file_url(:pop_up), :rel => "lightbox-pictures"}
              = image_tag attachment.file_url(:thumb)
            / = link_to "#{raw('<i class="icon-eye-open"></i>')} View Attachment".html_safe
          .imagelink_bottom{:style => "height:50px; width:100px; float: left; clear:both;"}
            = link_to "#{raw('<i class="icon-trash"></i>')} Delete Attachment".html_safe, attachment_path(attachment), :confirm => "Are you sure you want to delete this attachment?", :method => :delete
  .span6
    = form_for @project, :html => {:multipart => true} do |f|
      = f.error_messages
      = f.fields_for :attachments do |ff|
        %b
        - if @project.attachments.count < 5
          - if ff.object.new_record?
            %h3 Attach Additional Media
            = ff.label :file, "Upload a picture attachment"
            = ff.file_field :file, :style => "padding-bottom: 10px;"
            %br
            = ff.text_field :remote_file_url, :placeholder => "Or use an image URL", :class => "span12", :style => "width: 100%;"
      .row-fluid
        .span12
          %h3 Video URL
          = f.text_field :video_url
      .row-fluid
        .span12
          %center
            = f.submit "Save Media", :class => "btn btn-danger btn-project"

%br
  %center
    -unless @project.video_url.blank?
      = vid_embed_video(@project.video_url).html_safe

app/views/projects/_attachments_form.html.haml
.row-fluid
  .span6
    %h4.edit_header Existing Media
    - @project.attachments.each do |attachment|
      - unless attachment.new_record?
        .image_container{:style => "background-image: url(#{attachment.file_url(:thumb)})"}
          .imagelink_top{:style => "height:50px; width:100px; float: left; clear:both;"}  
            %a{:href => attachment.file_url(:pop_up), :rel => "lightbox-pictures"}
              = image_tag attachment.file_url(:thumb)
            / = link_to "#{raw('<i class="icon-eye-open"></i>')} View Attachment".html_safe
          .imagelink_bottom{:style => "height:50px; width:100px; float: left; clear:both;"}
            = link_to "#{raw('<i class="icon-trash"></i>')} Delete Attachment".html_safe, attachment_path(attachment), :confirm => "Are you sure you want to delete this attachment?", :method => :delete
    -unless @project.video_url.blank?
      = editpage_embed_video(@project.video_url).html_safe

  .span6
    = form_for @project, :html => {:multipart => true} do |f|
      = f.error_messages
      = hidden_field_tag :step, @breadcrumb_name
      = f.fields_for :attachments do |ff|
        %b
        - if @project.attachments.count < 6
          - if ff.object.new_record?
            %h4.edit_header Attach Additional Media
            = ff.label :file, "Upload a picture attachment"
            = ff.file_field :file, :style => "padding-bottom: 10px;"
            %br
            = ff.text_field :remote_file_url, :placeholder => "Or use an image URL", :class => "span12", :style => "width: 100%;"
      .row-fluid
        .span12
          %h4.edit_header Video URL
          = f.label :video_url, "Add a link to a short video about your project"
          = f.text_field :video_url, :placeholder => "Only Youtube or Vimeo links are supported at this time", :class => "span12", :style => "width: 100%;"
      .row-fluid
        .span12
          %center
            = f.submit "Save Media", :class => "btn btn-primary btn-project"

app/views/projects/_comment_form.html.haml
= f.error_messages
= f.hidden_field :commentable_id, :value => @project.id
= f.hidden_field :commentable_type, :value => 'Project'
= f.text_field :body, :class => "span12", :style => "width: 100%; max-width: 100%;"
= submit_tag "Post Comment", :class => "btn btn-danger btn-small"

app/views/projects/_existing_members.html.haml
.well_two{:style => "padding:10px; margin-bottom: 0px;"}
  .row-fluid
    .span2
      = image_tag membership.account.avatar_url(:small_thumb)
    .span10
      = membership.account.name
      .minifont= "Joined: #{(membership.created_at).strftime("%m/%d/%Y")}"
      .minifont
        -if membership.account.linked_in? 
          = link_to "#{raw('<i class="icon-linkedin-sign"></i>')} Linked In".html_safe, linkedinurl(membership.account.linked_in), :target => "_blank"
          = "  /  "
        -if active_member?(@project)
          = link_to "#{raw('<i class="icon-remove-sign"></i>')} Remove Member".html_safe, membership_path(membership), :confirm => "Are you sure you want to delete this membership?", :method => :delete
          = " / "
        %a{:href => "mailto:#{membership.account.email}"}
          %i.icon-envelope
          Email User
%br

app/views/projects/_form.html.haml
.row-fluid
  .span12
    = form_for @project, :html => {:multipart => true} do |f|
      = f.error_messages
      %h3 General Information
      .row-fluid
        .span6
          = f.label :business_name
          = f.text_field :business_name, :class => "span12", :style => "width: 100%;"
          = f.label :industry
          = f.select :industry, INDUSTRIES, {:include_blank => 'No Selection'}, :class => "span12", :style => "width: 100%;"
          = f.label :city
          = f.text_field :city, :class => "span12", :style => "width: 100%;"
          = f.label :state
          = f.select :state, STATES, {:include_blank => 'No Selection'}, :class => "span12", :style => "width: 100%;"
        .span6
          = f.label :logo, "Business Logo"
          = f.file_field :logo, :style => "padding-bottom: 10px;"
          = f.label :business_plan, "Upload a business plan"
          = f.file_field :business_plan, :style => "padding-bottom: 10px;"
          = f.label :business_concept
          = f.text_area :business_concept, :class => "span12", :style => "width: 100%; max-width: 100%; max-height: 87px;"
      .row-fluid
        .span12
          %center
            = f.submit "Save Project", :class => "btn btn-danger btn-project"

    = render 'memberships'
    = render 'attachments'

app/views/projects/_general_form.html.haml
.row-fluid
  .span12
    = form_for @project, :html => {:multipart => true} do |f|
      = f.error_messages
      %h4.edit_header General Information
      = hidden_field_tag :step, @breadcrumb_name
      .row-fluid
        .span6
          = f.label :business_name
          = f.text_field :business_name, :class => "span12", :style => "width: 100%;"
          = f.label :industry
          = f.select :industry, INDUSTRIES, {:include_blank => 'No Selection'}, :class => "span12", :style => "width: 100%;"
          = f.label :city
          = f.text_field :city, :class => "span12", :style => "width: 100%;"
          = f.label :state
          = f.select :state, STATES, {:include_blank => 'No Selection'}, :class => "span12", :style => "width: 100%;"
        .span6
          = f.label :logo, "Business Logo"
          = f.file_field :logo, :style => "padding-bottom: 10px;"
          = f.label :business_plan, "Upload a business plan"
          = f.file_field :business_plan, :style => "padding-bottom: 10px;"
          = f.label :business_concept
          = f.text_area :business_concept, :class => "span12", :style => "width: 100%; max-width: 100%; max-height: 120px;"
      .row-fluid
        .span12
          %center
            = f.submit "Save Project", :class => "btn btn-primary btn-project"

app/views/projects/_memberships.html.haml
.row-fluid
  .span6
    %h3 Current Team Members
    - @project.memberships.each do |membership|
      %tr
        %td= membership.account.name
        %td= link_to "Remove Member", membership_path(membership), :confirm => "Are you sure you want to delete this membership?", :method => :delete
      %br
    %h3 Pending Team Members 
    %p (These members are only viewable during editing)
    - @project.pending_memberships.each do |pmember|
      %tr
        %td= pmember.account.label
        %td= link_to "Cancel invitation", membership_path(pmember), :confirm => "Are you sure you want to delete this invitation?", :method => :delete
      %br
    - @project.invitations.each do |invite|
      %tr
        %td= invite.label
        %td= link_to "Cancel invitation", invitation_path(invite), :confirm => "Are you sure you want to delete this invitation?", :method => :delete
      %br
  .span6
    %h3 Add New Team Member
    = form_for @project, :html => {:multipart => true} do |f|
      = f.error_messages
      = f.fields_for :invitee_attributes do |ff| 
        = ff.label :name, "Name"
        = ff.text_field :name
        = ff.label :email, "Email"
        = ff.email_field :email, :class => "span12", :style => "width: 100%;"
      .row-fluid
        .span12
          %center
            = f.submit "Save Memberships", :class => "btn btn-danger btn-project"

app/views/projects/_memberships_form.html.haml
.row-fluid
  .span6
    %h4.edit_header Current Team Members
    - @project.memberships.each do |membership|
      = render 'existing_members', :membership => membership unless membership.pending?
    %h4 Pending Team Members 
    %p (These members are only viewable during editing)
    - @project.pending_memberships.each do |pmember|
      .well_two{:style => "padding:10px; margin-bottom: 0px;"}
        .row-fluid
          .span12
            = pmember.account.label
            .minifont= "Invited: #{(pmember.created_at).strftime("%m/%d/%Y")}"
            .minifont= link_to "#{raw('<i class="icon-trash"></i>')} Cancel Invitation".html_safe, membership_path(pmember), :confirm => "Are you sure you want to delete this invitation?", :method => :delete
      %br
    / %h4.edit_header Invited Team Members
    - @project.invitations.each do |invite|
      .well_two{:style => "padding:10px; margin-bottom: 0px;"}
        .row-fluid
          .span12
            = invite.label
            .minifont= "Invited: #{(invite.created_at).strftime("%m/%d/%Y")}"
            .minifont= link_to "#{raw('<i class="icon-trash"></i>')} Cancel Invitation".html_safe, invitation_path(invite), :confirm => "Are you sure you want to delete this invitation?", :method => :delete
      %br
  .span6
    %h4.edit_header Add New Team Member
    = form_for @project, :html => {:multipart => true} do |f|
      = f.error_messages
      = hidden_field_tag :step, @breadcrumb_name
      = f.fields_for :invitee_attributes do |ff| 
        = ff.label :name, "Name"
        = ff.text_field :name, :class => "span12", :style => "width: 100%;"
        = ff.label :email, "Email"
        = ff.email_field :email, :class => "span12", :style => "width: 100%;"
      .row-fluid
        .span12
          %center
            = f.submit "Save Memberships", :class => "btn btn-primary btn-project"

app/views/projects/_notifications.html.haml
= form_for :notification, url: notifications_path do |n|
  = n.hidden_field :notifier_id, :value => @project.id
  = n.hidden_field :notifier_type, :value => "Project"
  = render "shared/notification_form", :n => n 

app/views/projects/edit.html.haml
#mainhub.span9
  .row-fluid
    .span9
      .row-fluid
        .span12
          = render 'shared/breadcrumbs'
      
      .well     
        .row-fluid
          .span12
            .row-fluid{:style => "margin-bottom:18px;"}
              .span12
                %h1.projectnamefont{:style => "text-align: top;"}= @project.business_name
            = render "#{@breadcrumb_name.downcase}_form"
    .span3
      = render 'shared/side_menu' 

app/views/projects/index.html.haml
#mainhub.span9
  .well
    .row-fluid
      .span12
        %h4.edit_header All Published Projects at Georgia State University
        %table.table.table-striped
          %thead
            %tr
              %th
                Project Name
              %th
                Date Started
              %th
                %center
                  Team Members
              %th
                %center
                  Recruiting?
              %th
                %center
                  No. of Competitions Entered
          %tbody
            - @projects.each do |project|
              %tr
                %td
                  = image_tag project.logo_url(:tiny_thumb)
                  -if project.published?
                    %a{:href => project_path(project.id)}
                      = project.business_name
                  -else
                    = project.business_name
                %td
                  = project.created_at.strftime("%d/%m/%Y")
                %td
                  %center
                    = project.memberships.where(:pending => "false").count
                %td
                  %center
                    - if project.notifications.where(:notification_type => "Recruiting").count > 0
                      = link_to "Yes", project_notifications_path(project, :notification_type => "Recruiting")
                %td
                  %center
                    1

app/views/projects/new.html.haml
#mainhub.span9
  .well
    .row-fluid
      .span12
        %h1.projectnamefont New Project
    = form_for @project do |f|
      .row-fluid{:style => "margin-top:18px;"}
        .span12
          = f.error_messages

      .row-fluid
        .span6
          = f.label :business_name
          = f.text_field :business_name, :class => "span12", :style => "width: 100%;"
          = f.label :industry
          = f.select :industry, INDUSTRIES, {:include_blank => 'No Selection'}, :class => "span12", :style => "width: 100%;"
          = f.label :city
          = f.text_field :city, :class => "span12", :style => "width: 100%;"
          = f.label :state
          = f.select :state, STATES, {:include_blank => 'No Selection'}, :class => "span12", :style => "width: 100%;"
        .span6
          = f.label :logo, "Business Logo"
          = f.file_field :logo, :style => "padding-bottom: 10px;"
          = f.label :business_concept
          = f.text_area :business_concept, :class => "span12", :style => "width: 100%; max-width: 100%; max-height: 147px;"
      .row-fluid
        .span12
          %center
            = f.submit "Save Project", :class => "btn btn-primary btn-small btn-project"

app/views/projects/show.html.haml
#mainhub.span9
  .row-fluid
    .span9
      .row-fluid
        .span12
          =render 'shared/breadcrumbs'
      .well
        .row-fluid{:style => "margin-bottom:18px;"}
          .span12
            %h1.projectnamefont{:style => "text-align: top;"}= @project.business_name
        
        -if @project.video_url.present? || @project.attachments.count > 1
          .row-fluid
            .span12
              %h4.edit_header= "#{raw('<i class="icon-picture"></i>')} Project Media".html_safe
              #image_container.image_container_scroll
                -if @project.video_url.present?
                  %iframe.image_property{:width => "445", :height =>"250", :src => "#{vid_link(@project.video_url)}"}
                - @project.attachments.each do |imageattachment|
                  %a{:href => imageattachment.file_url(:pop_up), :rel => "lightbox-pictures", :style => "text-decoration:none; border:0px;"} 
                    =image_tag imageattachment.file_url(:big_thumb), :class => "image_property"
        .row-fluid
          .span6
            %h4.edit_header= "#{raw('<i class="icon-info-sign"></i>')} Project Information".html_safe
            %h5
              %i.icon-pushpin
              Business Concept
            %p= @project.business_concept

            %h5
              %i.icon-briefcase
              Industry
            %p= @project.industry

            %h5
              %i.icon-map-marker
              Location
            %p= "#{@project.city}, #{@project.state}"
              
          .span6
            %h4.edit_header= "#{raw('<i class="icon-group"></i>')} Team Members".html_safe
            - unless @project.notifications.count(:conditions => {:notification_type => "Recruiting"}) == 0 or nil
              .alert.alert-success
                %h4 We're Looking For People To Join Our Team!
                %p.minifont Click the link below to view our recruiting notifications. You can read a description of what we're looking for and you can contact us if you're interested!
                %p.minifont= link_to "Recruiting Notifications", project_notifications_path(@project, :notification_type => "Recruiting")
            - @project.memberships.each do |membership|
              = render 'existing_members', :membership => membership unless membership.pending?
          
                
    .span3
      =render 'shared/side_menu'